name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:21-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ./gradlew
      - run: ./gradlew checkVersion build publish --stacktrace
        env:
          SNAPSHOTS_MAVEN_URL: ${{ secrets.SNAPSHOTS_MAVEN_URL }}
          SNAPSHOTS_MAVEN_USERNAME: ${{ secrets.SNAPSHOTS_MAVEN_USERNAME }}
          SNAPSHOTS_MAVEN_PASSWORD: ${{ secrets.SNAPSHOTS_MAVEN_PASSWORD }}
